services:
  api:
    build: .
    container_name: hand_gesture_api
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
