name: Build and Push Docker Image to Azure Container Registry

on:
  push:
    branches:
      - main # or your desired branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI - Log in to ACR
        run: |
          az acr login --name ${{ secrets.AZURE_REGISTRY_NAME }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/handgesture:latest .
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/handgesture:latest
